### ISSUE TITLE
Splash page/site for people

### ISSUE THREAD

**Issue by rmagee88** [fortunate-giraffe/memes-for-mankind#130]
Not part of the game, just a page explaning it and us... linking to chromecast store and our app.

**Comment by ajkitson** [comment]
Also, if we have time, a site for :hamster: -s

**Comment by rmagee88** [comment]
https://wrapbootstrap.com/ - bunch of options for pre set glossy sites we could use as a landing page

**Comment by ajkitson** [comment]
Need to update communication section

**Comment by rmagee88** [comment]
placeholders for Play Store / iOS Store
