### ISSUE TITLE
Refactor messenger services to handle local dev and chromecast

### ISSUE THREAD

**Issue by ajkitson** [fortunate-giraffe/memes-for-mankind#150]

**Comment by ajkitson** [comment]
We need better separation of concerns for our messaging. It's all over the place right now and hard to modify. Adding ChromeCast was tough. Supporting Cordova could be really difficult until we fix it.

The goal is to have a single file, each with a factory, that does one thing. Here's the target breakdown:
- game-messenger/player-messenger. Controllers and game logic can use the messengers to listen for events in the game and send messages in terms of the game (e.g. players ready). These modules have no knowledge of whether they are communicating over cast or sockets or something else. Their job is solely to translate game-specific logic into generic messaging terms (e.g. playersReady() -> send('playersReady'))
- messaging/messenger. This module figures out what messaging platform to use and gives it to game-messenger/player-messenger.
- sockets / CC-player / CC-receiver. These modules translate the generic messaging terms into terms specific to the messaging platform. For example, it will take send('playersReady') and translate it to socket.send('playersReady'). It will also handle any initialization.

As a first pass, we'll just sort concerns into separate modules and files. As a second pass, we can take a look at where those modules are located in the repo.

**Comment by rmagee88** [comment]
One thought- I'm changing the way we use constants (localDev, for
instance)- so just a heads up that there will likely be more and some
slightly different constants involved.

-Rich

**Comment by ajkitson** [comment]
Sounds good. As long as I can inject them.

**Comment by ajkitson** [comment]
Might be worthwhile to create modules for:
- even handling
- message building and parsing
- where does message queueing belong?
  But hold off on this until other modules are sorted.

**Comment by ajkitson** [comment]
Messaging platforms must all implement the following methods:
- connect
- send
- broadcast
- onready
- onmessage
- connectionStatus

If it doesn't apply to a given platform, we'll just have an empty function

**Comment by ajkitson** [comment]
Splitting this out into a few issues:
- Sockets working 
- Cast sender
- Cast receiver
