### ISSUE TITLE
Mobile: figure out deployment/repo changes

### ISSUE THREAD

**Issue by ajkitson** [fortunate-giraffe/memes-for-mankind#204]

**Comment by ajkitson** [comment]
Things I changed the first time around to get m4m to compile in Cordova. Just listing them here as a starting point--not endorsing this as a strategy:

### Copy stuff over
- Copy `/sender-app` to `Cordova/www`
- Copy `/core` to `Cordova/www`
- Copy `/bower_components` to `Cordova/www`

### Update index.html and resolve links
- Combine Cordova's index.html and `sender-app/index.html`. Specifically, we need the two JS files Cordova includes, maybe some of the other stuff
- Move sender/index.html to the top level folder, where Cordova expects it
- Update all the references in index.html
- Update links in ui-router, specifically the links to view templates
- Update links in shell.html and header.html

### Update Angular bootstrapping
- Remove ng-app directive from index.html
- In `Cordova/js/index/js`, add code to bootstrap Angular on the deviceReady event: `angular.bootstrap(document.getElementsByTagName('html')[0], ["app"])`
- Install the console plugin so you can see what's going on

**Comment by ajkitson** [comment]
Once the ios and android projects are set up (with dependencies, etc), we might not need to build them again. Maybe we can just move any updated files into their respective www directories--worth testing as that could simplify things.

**Comment by ajkitson** [comment]
Here's what I'm trying as a first pass. The general strategy is that we'll have two sender-app directories, one for the web, one for mobile. This will entail duplication, but it'll at least get us up and running. Once we've got it working, we can see what duplicated code we can move back to a shared base. A general restructure of the repo would help here. If we can ensure that the sender app (both mobile and web) has everything it needs within its own directory (i.e. doesn't reach out to /core), we should be able to share all the files except the index.html, which shouldn't be hard to do separately.

Alright, here's the plan:

### Move files to new folder in the repo
- create a blank cordova app in /client, under a sender-app-mobile directory
- delete default css, img, js files, after copying out index.js (for reference)
- copy sender-app files into sender-app-mobile/www
- copy /core files into sender-app-mobile/www,
- copy /bower_components to their own subfolder 
- update links in index.html (but shouldn't have to update elsewhere since relative paths within sender-app are the same
- run a python server and check that all links are resolving (need a server for ajax stuff)
- add cordova.js to our index.html
- remove ng-app from index.html
- bootstrap our app on deviceReady event. Maybe get rid of Cordova's index.js altogether (update: definitely get rid of it, just contains the device ready handler)
- try out with sockets
- update .gitignore to only include /www (maybe should also include entire ios folder ... I dunno)

### Install Plugins
- install console.log plugin
- install ConnectSDK
- test that we can build
- test that ConnectSDK is available in JS

### Build out messaging platform for ConnectSDK
- Skeleton new messaging platform
- Update messaging.js to pull in new platform (if not sockets)
- Implement init and connect
- Try it out!
- Implement remaining methods
- Try it out!

If this works, then should be able to play the game from the emulator while everyone else plays from their laptops. Will then need to figure out how to get everyone else set up to do dev.

**Comment by ajkitson** [comment]
Got through moving all the files and it works with sockets. This might be a Grunt-able step.

Decided to exclude platforms in gitignore. Committing everything else for now

**Comment by ajkitson** [comment]
Now installing plugins. I'm going to leave the app set up to use sockets until I can get it to compile with the plugins installed. Then I'll switch over to the Connect SDK

**Comment by ajkitson** [comment]
Not sure how/if we'll track the ConnectSDK bundle with git.

**Comment by ajkitson** [comment]
Got plugins working, or at least was able to install the plugins, add dependencies, and run the app. Not yet using ConnectSDK

**Comment by rmagee88** [comment]
Got the app to load on Android (and documented steps to get there)... pretty easy :D

**Comment by rmagee88** [comment]
Also got the message passing to work!!!!!!!!!!!... updated receivertest to use 'urn:x-cast:com.connectsdk' instead of 'vandelay-industries'

I think we're done with mobile??

**Comment by ajkitson** [comment]
Updated Cordova to use its own html file: mobile.html. 
Moved cast-sender-mobile.js to main core/mobile-platforms directory

The rest can be taken care of with grunt tasks to:
- copy sender-app to sender-app-mobile/www
- copy bower_components to sender-app-mobile/www/
- copy core to sender-app-mobile/www

We could clean up the repo further to split out core but there's no driving need at this point
