### ISSUE TITLE
Set up HTTPS before going live

### ISSUE THREAD

**Issue by ajkitson** [fortunate-giraffe/memes-for-mankind#38]
Required for production apps

**Comment by rmagee88** [comment]
I did this for my blog and on my last project so can help with this... used startssl and it was pretty easy/free

We'll want to get a top-level domain to go with this as well if we go down this route

**Comment by ajkitson** [comment]
Check out cloudfare free SSL for heroku: https://robots.thoughtbot.com/set-up-cloudflare-free-ssl-on-heroku

**Comment by ajkitson** [comment]
The HTTPS requirement applies only to the receiver app. Since Heroku apps are served over https by default if you use herokuapp.com domain we can just use that since nobody sees the receiver app url. Also, we're not handling any sensitive data--no login, just text for memes--so don't need SSL for the player communication.
