### ISSUE TITLE
Set up shared Receiver server

### ISSUE THREAD

**Issue by ajkitson** [fortunate-giraffe/memes-for-mankind#45]
To run the receiver code on ChromeCast, even for testing, the receiver code needs to be at a publicly accessible URL. 

We need a way to develop code and push it to a URL the ChromeCast can access. This should probably be separate from the production deployment. All team members should be able to push code to this server for testing.

Other ideas:
- each of us configures our own application with Google. Do we need to share it for local dev?
- use ngrok for local dev so you don't need to push the code anywhere

**Comment by ajkitson** [comment]
A few more thought-out setups:
Individual registered apps and ngrok
- Each of us has a separate app set up in our own dev console. 
- We run ngrok to allow ChromeCast to get the receiver app from our local computer. 
- Because we have our own app in our own dev console, we can update the URL at will. 
- We will then need to make sure that the appID is not committed, or at least is configurable for local dev vs. deployment. The appID will have to be our own appID.
- We will need to register the ChromeCasts in each of our dev consoles (probably)

Summing up: more freedom, but could lead to issues keeping code/appIDs in sync, later integrating with production deployment process, etc. 

Shared registered app and shared publicly deployed
- There is one registered app 
- There is one location we push non-prd changes to the receiver app, probably setting it up to pull from a non-master github branch. Alternatively, could set up remote repo we can all push to (easier up front, but could lead to weird git issues since it'd be harder to maintain a common git history)
- Would have to commit and deploy changes to test server to see if code works (or at least that it works on a chromecast)

Summing up: less messing around with app IDs and enforces discipline about deployment, but only one person can make changes touching the receiver at a time and there's extra overhead for testing.

Maybe we want to do a combo of these, using ngrok when getting started and then the deployed test server as a final check to make sure the code looks good

**Comment by ajkitson** [comment]
Can also host static files on Google Drive: 
https://support.google.com/drive/answer/2881970?hl=en

**Comment by i-made-that** [comment]
We can revisit the emulator as well: 
https://github.com/dz0ny/leapcast

**Comment by ajkitson** [comment]
Putting for W-Th milestone as it's not yet blocking our progress, but it'll have to be first thing W in order to tie everything together and have a working MVP

**Comment by ajkitson** [comment]
For dev, ended up mocking messaging with sockets. Then we have a shared dev heroku instance for testing w/Cast
